### ISSUE TITLE
Could not create cudnn handle & Possibly insufficient driver version

### ISSUE THREAD

**Issue by saskra** [pcpLiu/DeepSeqPan#2]
I have a problem with the GPU version:

```
~/projects/DeepSeqPan/scripts$ python runner.py --train
Using TensorFlow backend.
2018-10-16 10:07:35.808646: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2018-10-16 10:07:38.048505: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties:
name: Tesla V100-PCIE-16GB major: 7 minor: 0 memoryClockRate(GHz): 1.38
pciBusID: 0000:3b:00.0
totalMemory: 15.78GiB freeMemory: 15.36GiB
2018-10-16 10:07:38.383778: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 1 with properties:
name: Tesla V100-PCIE-16GB major: 7 minor: 0 memoryClockRate(GHz): 1.38
pciBusID: 0000:d8:00.0
totalMemory: 15.78GiB freeMemory: 15.36GiB
2018-10-16 10:07:38.385505: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0, 1
2018-10-16 10:07:39.098841: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-10-16 10:07:39.098884: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      0 1
2018-10-16 10:07:39.098891: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0:   N Y
2018-10-16 10:07:39.098895: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 1:   Y N
2018-10-16 10:07:39.099423: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14864 MB memory) -> physical GPU (device: 0, name: Tesla V100-PCIE-16GB, pci bus id: 0000:3b:00.0, compute capability: 7.0)
2018-10-16 10:07:39.100600: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 14864 MB memory) -> physical GPU (device: 1, name: Tesla V100-PCIE-16GB, pci bus id: 0000:d8:00.0, compute capability: 7.0)
================================================================================
Train new model on [bdata.20130222.mhci.txt]
================================================================================
2018-10-16 10:07:39.141214: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0, 1
2018-10-16 10:07:39.141283: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-10-16 10:07:39.141293: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      0 1
2018-10-16 10:07:39.141317: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0:   N Y
2018-10-16 10:07:39.141323: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 1:   Y N
2018-10-16 10:07:39.141752: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14864 MB memory) -> physical GPU (device: 0, name: Tesla V100-PCIE-16GB, pci bus id: 0000:3b:00.0, compute capability: 7.0)
2018-10-16 10:07:39.142052: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 14864 MB memory) -> physical GPU (device: 1, name: Tesla V100-PCIE-16GB, pci bus id: 0000:d8:00.0, compute capability: 7.0)

Epoch 1/1000
2018-10-16 10:07:55.381849: E tensorflow/stream_executor/cuda/cuda_dnn.cc:353] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED
2018-10-16 10:07:55.381944: E tensorflow/stream_executor/cuda/cuda_dnn.cc:361] Possibly insufficient driver version: 390.87.0
Segmentation fault (core dumped)
```

_OS Platform and Distribution:_ **Ubuntu 18.04.1 LTS**
_TensorFlow installed from:_ **conda**
_TensorFlow version:_ **1.11.0**
_CUDA/cuDNN version:_ **9.0.176/ 7.3.1**
_GPU model and memory:_ **Tesla V100-PCIE-16GB**

Is it really the driver version being the problem? Which one are you using?

**Comment by pcpLiu** [comment]
Hi @saskra ,
I'm not sure what happened in your situation. But it looks to me a TF compatibility problem. Some people also meet your situations using TF, you may follow some instructions from other's suggestions:
- https://github.com/tensorflow/tensorflow/issues/21832
- https://stackoverflow.com/questions/41409842/ubuntu-16-04-cuda-8-cuda-driver-version-is-insufficient-for-cuda-runtime-vers
- https://devtalk.nvidia.com/default/topic/1042575/cuda-driver-version-is-insufficient-for-cuda-runtime-version/?offset=2#5289688

Another thing I notice is that your TF version is newer than ours. But I'm not sure if it's the root problem. You can install then older version and give it a try, 

I clone and run the code on our machine.  Everything works well for me. I attached my TF running log and our environment. Hope it helps. :)

**Running log:**
```
python runner.py --train
/home/root/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
================================================================================
Train new model on [bdata.20130222.mhci.txt]
================================================================================


2018-10-16 14:16:22.582671: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-10-16 14:16:22.583243: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1212] Found device 0 with properties: 
name: TITAN V major: 7 minor: 0 memoryClockRate(GHz): 1.455
pciBusID: 0000:22:00.0
totalMemory: 11.78GiB freeMemory: 10.88GiB
2018-10-16 14:16:22.583277: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1312] Adding visible gpu devices: 0
2018-10-16 14:16:26.961755: I tensorflow/core/common_runtime/gpu/gpu_device.cc:993] Creating TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10518 MB memory) -> physical GPU (device: 0, name: TITAN V, pci bus id: 0000:22:00.0, compute capability: 7.0)
Epoch 1/1000
2555/6105 [===========>..................] - ETA: 2:37 - loss: 106.5268 - regression_output_loss: 10.9749 - classify_output_loss: 0.5368
```

**Environment:**
- CUDA driver:  **390.87**
- CUDA version:  **9.0**
- TensorFLow version: **1.6.0**
- GPU: **TITAN V**
- CUDNN: **not installed** 
- OS: **Ubuntu 16.04.5 LTS**

**Comment by saskra** [comment]
Thanks a lot, it is working now! In the end, the problem was that it did not use the system's Cudnn version but an incompatible version which came with the creation of the Anaconda environment. By overwriting this with the system's version manually I could solve the problem. This way, I did not have to change the driver or Tensorflow.

**Comment by lijian-1994** [comment]
@saskra since i got the same problem,how do you solve it?Thank you very much!

**Comment by saskra** [comment]
I followed this Tutorial: https://github.com/pplcc/ubuntu-tensorflow-pytorch-setup
